name: Test

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

env:
  CI: false

jobs:
  deploy:
    name: Test
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test
